# Generated by Django 6.0.6 on 2026-06-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_music_data_alter_music_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_data',
            field=models.FileField(upload_to='musics/'),
        ),
    ]
